local tlsp = require('telescope.builtin')

-- Buffer local mappings.
-- See `:help vim.lsp.*` for documentation on any of the below functions
vim.keymap.set('i', '<C-h>', vim.lsp.buf.signature_help)
vim.keymap.set({ 'n', 'v' }, '<leader>vca', vim.lsp.buf.code_action)
vim.keymap.set('n', '<leader>vd', vim.diagnostic.open_float)
vim.keymap.set('n', '<leader>vrn', vim.lsp.buf.rename)
vim.keymap.set('n', '<leader>vrr', tlsp.lsp_references)
vim.keymap.set('n', '<leader>vws', tlsp.lsp_workspace_symbols)
vim.keymap.set('n', '<leader>wa', vim.lsp.buf.add_workspace_folder)
vim.keymap.set('n', '<leader>wr', vim.lsp.buf.remove_workspace_folder)
vim.keymap.set('n', '<leader>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
end)
vim.keymap.set('n', '<leader>f', function()
    vim.lsp.buf.format { async = true }
end)
vim.keymap.set('n', 'K', vim.lsp.buf.hover)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
vim.keymap.set('n', 'gD', vim.lsp.buf.declaration)
vim.keymap.set('n', 'gd', tlsp.lsp_definitions)
vim.keymap.set('n', 'gi', tlsp.lsp_implementations)
vim.keymap.set('n', '<leader>D', tlsp.lsp_type_definitions)
